# Generated by Django 4.2 on 2023-04-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRegister_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('DateOfBirth', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
