# Generated by Django 4.2 on 2023-04-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregister_tb',
            name='Status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
