# Generated by Django 4.2 on 2023-04-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_category_tb'),
        ('seller', '0002_alter_sellerregister_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='')),
                ('Price', models.CharField(max_length=20)),
                ('Stock', models.CharField(max_length=20)),
                ('Details', models.CharField(max_length=20)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.category_tb')),
                ('SellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerregister_tb')),
            ],
        ),
    ]
