# Generated by Django 4.2 on 2023-04-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_orders_tb_status'),
        ('seller', '0003_product_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('Details', models.CharField(max_length=20)),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.orders_tb')),
            ],
        ),
    ]
