# Generated by Django 4.2 on 2023-04-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_tracking_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='Stock',
            field=models.IntegerField(max_length=20),
        ),
    ]
