# Generated by Django 4.2 on 2023-04-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_product_tb_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='Stock',
            field=models.IntegerField(),
        ),
    ]
