# Generated by Django 4.2 on 2023-04-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_cart_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='Total',
            field=models.IntegerField(),
        ),
    ]
