# Generated by Django 4.2 on 2023-04-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_alter_cart_tb_quantity_alter_cart_tb_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_tb',
            old_name='ShippingDate',
            new_name='ShippingAddress',
        ),
    ]
