# Generated by Django 4.2 on 2023-04-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_rename_shippingdate_cart_tb_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('Total', models.IntegerField()),
                ('OrderDate', models.CharField(max_length=20)),
                ('OrderTime', models.CharField(max_length=20)),
                ('BuyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerregister_tb')),
            ],
        ),
    ]
