# Generated by Django 4.2 on 2023-04-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_tb'),
        ('buyer', '0005_orders_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersItem_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('BuyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerregister_tb')),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.orders_tb')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_tb')),
            ],
        ),
    ]
