# Generated by Django 4.2 on 2023-04-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_ordersitem_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_tb',
            name='Total',
        ),
    ]
