# Generated by Django 4.2 on 2023-04-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_remove_orders_tb_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_tb',
            name='Status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
