# Generated by Django 4.2 on 2023-04-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_orders_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_tb',
            name='Status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
