# Generated by Django 4.2 on 2023-04-26 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_orders_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Name', models.CharField(max_length=20)),
                ('Card_Number', models.CharField(max_length=20)),
                ('Cvv', models.CharField(max_length=20)),
                ('Exp_Date', models.CharField(max_length=20)),
                ('BuyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerregister_tb')),
                ('Order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.orders_tb')),
            ],
        ),
    ]
