# Generated by Django 4.2 on 2023-04-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_payment_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_tb',
            name='Grand_Total',
            field=models.IntegerField(default=0),
        ),
    ]
